In [16]:
import pandas as pd
import numpy as np
import ucimlrepo
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
census_income_kdd = fetch_ucirepo(id=117) 
  
# data (as pandas dataframes) 
X = census_income_kdd.data.features 
y = census_income_kdd.data.targets 
  
# metadata 
print(census_income_kdd.metadata) 
  
# variable information 
print(census_income_kdd.variables)

{'uci_id': 117, 'name': 'Census-Income (KDD)', 'repository_url': 'https://archive.ics.uci.edu/dataset/117/census+income+kdd', 'data_url': 'https://archive.ics.uci.edu/static/public/117/data.csv', 'abstract': 'This data set contains weighted census data extracted from the 1994 and 1995 current population surveys conducted by the U.S. Census Bureau.', 'area': 'Social Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 299285, 'num_features': 41, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Occupation', 'Education Level', 'Marital Status', 'Race', 'Sex', 'Other', 'Nationality', 'Income'], 'target_col': ['income'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2000, 'last_updated': 'Fri Mar 08 2024', 'dataset_doi': '10.24432/C5N30T', 'creators': [], 'intro_paper': None, 'additional_info': {'summary': "This data set contains weighted census data extracted from the 1994 and 1995 Current Population Surveys conducted by the U.S. Census Bureau. The data contains 41 demographic and employment related variables. \r\n\r\nThe instance weight indicates the number of people in the population that each record represents due to stratified sampling. To do real analysis and derive conclusions, this field must be used. This attribute should *not* be used in the classifiers. \r\n\r\nOne instance per line with comma delimited fields. There are 199523 instances in the data file and 99762 in the test file. \r\n\r\nThe data was split into train/test in approximately 2/3, 1/3 proportions using MineSet's MIndUtil mineset-to-mlc. \r\n", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'More information detailing the meaning of the attributes can be found in the Census Bureau\'s documentation To make use of the data descriptions at this site, the following mappings to the Census Bureau\'s internal database column names will be needed: \r\n\r\nage\t\t\t\t\t\tAAGE\r\nclass of worker\t\t\t\t\tACLSWKR\r\nindustry code\t\t\t\t\tADTIND\r\noccupation code\t\t\t\t\tADTOCC\r\nadjusted gross income\t\t\t\tAGI\r\neducation\t\t\t\t\tAHGA\r\nwage per hour\t\t\t\t\tAHRSPAY\r\nenrolled in edu inst last wk\t\t\tAHSCOL\r\nmarital status\t\t\t\t\tAMARITL\r\nmajor industry code\t\t\t\tAMJIND\r\nmajor occupation code\t\t\t\tAMJOCC\r\nmace\t\t\t\t\t\tARACE\r\nhispanic Origin\t\t\t\t\tAREORGN\r\nsex\t\t\t\t\t\tASEX\r\nmember of a labor union\t\t\t\tAUNMEM\r\nreason for unemployment\t\t\t\tAUNTYPE\r\nfull or part time employment stat\t\tAWKSTAT\r\ncapital gains\t\t\t\t\tCAPGAIN\r\ncapital losses\t\t\t\t\tCAPLOSS\r\ndivdends from stocks\t\t\t\tDIVVAL\r\nfederal income tax liability\t\t\tFEDTAX\r\ntax filer status\t\t\t\tFILESTAT\r\nregion of previous residence\t\t\tGRINREG\r\nstate of previous residence\t\t\tGRINST\r\ndetailed household and family stat\t\tHHDFMX\r\ndetailed household summary in household\t\tHHDREL\r\ninstance weight\t\t\t\t\tMARSUPWT\r\nmigration code-change in msa\t\t\tMIGMTR1\r\nmigration code-change in reg\t\t\tMIGMTR3\r\nmigration code-move within reg\t\t\tMIGMTR4\r\nlive in this house 1 year ago\t\t\tMIGSAME\r\nmigration prev res in sunbelt\t\t\tMIGSUN\r\nnum persons worked for employer\t\t\tNOEMP\r\nfamily members under 18\t\t\t\tPARENT\r\ntotal person earnings\t\t\t\tPEARNVAL\r\ncountry of birth father\t\t\t\tPEFNTVTY\r\ncountry of birth mother\t\t\t\tPEMNTVTY\r\ncountry of birth self\t\t\t\tPENATVTY\r\ncitizenship\t\t\t\t\tPRCITSHP\r\ntotal person income\t\t\t\tPTOTVAL\r\nown business or self employed\t\t\tSEOTR\r\ntaxable income amount\t\t\t\tTAXINC\r\nfill inc questionnaire for veteran\'s admin\tVETQVA\r\nveterans benefits\t\t\t\tVETYN\r\nweeks worked in year\t\t\t\tWKSWORK\r\n\r\nNote that Incomes have been binned at the $50K level to present a binary classification problem, much like the original UCI/ADULT database. The goal field of this data, however, was drawn from the "total person income" field rather than the "adjusted gross income" and may, therefore, behave differently than the orginal ADULT goal field. \r\n', 'citation': None}}
         name     role         type      demographic  \
0        AAGE  Feature      Integer              Age
1     ACLSWKR  Feature  Categorical             None
2      ADTINK  Feature      Integer             None
3      ADTOCC  Feature      Integer       Occupation
4        AHGA  Feature      Integer  Education Level
5      AHSCOL  Feature  Categorical  Education Level
6     AMARITL  Feature  Categorical   Marital Status
7      AMJIND  Feature  Categorical             None
8      AMJOCC  Feature  Categorical       Occupation
9       ARACE  Feature  Categorical             Race
10    AREORGN  Feature  Categorical             None
11       ASEX  Feature  Categorical              Sex
12     AUNMEM  Feature  Categorical             None
13    AUNTYPE  Feature  Categorical             None
14    AWKSTAT  Feature      Integer             None
15    CAPGAIN  Feature      Integer             None
16    GAPLOSS  Feature      Integer             None
17     DIVVAL  Feature  Categorical             None
18   FILESTAT  Feature  Categorical             None
19    GRINREG  Feature  Categorical             None
20     GRINST  Feature  Categorical             None
21     HHDFMX  Feature   Continuous            Other
22     HHDREL  Feature  Categorical             None
23  MARSUPWRT  Feature  Categorical             None
24    MIGMTR1  Feature  Categorical             None
25    MIGMTR3  Feature  Categorical             None
26    MIGMTR4  Feature  Categorical             None
27    MIGSAME  Feature      Integer             None
28     MIGSUN  Feature  Categorical             None
29      NOEMP  Feature  Categorical             None
30     PARENT  Feature  Categorical             None
31   PEFNTVTY  Feature  Categorical             None
32   PEMNTVTY  Feature      Integer             None
33   PENATVTY  Feature  Categorical      Nationality
34   PRCITSHP  Feature      Integer             None
35      SEOTR  Feature      Integer             None
36     VETQVA  Feature  Categorical             None
37      VETYN  Feature  Categorical             None
38    WKSWORK  Feature  Categorical             None
39     income   Target       Binary           Income
40    AHRSPAY  Feature      Integer             None
41       year  Feature      Integer             None

                                  description units missing_values
0                                         age  None             no
1                             class of worker  None             no
2                               industry code  None             no
3                             occupation code  None             no
4                                   education  None             no
5                   enrolled in edu last week  None             no
6                              marital status  None             no
7                         major industry code  None             no
8                       major occupation code  None             no
9                                        race  None             no
10                            hispanic origin  None             no
11                                        sex  None             no
12                    member of a labor union  None             no
13                    reason for unemployment  None             no
14          full or part time employment stat  None             no
15                              capital gains  None             no
16                             capital losses  None             no
17                      dividends from stocks  None             no
18                           tax filer status  None             no
19               region of previous residence  None             no
20                state of previous residence  None             no
21         detailed household and family stat  None             no
22    detailed household summary in household  None             no
23                            instance weight  None             no
24               migration code-change in msa  None            yes
25               migration code-change in reg  None            yes
26             migration code-move within reg  None            yes
27              live in this house 1 year ago  None             no
28              migration prev res in sunbelt  None            yes
29            num persons worked for employer  None             no
30                    family members under 18  None             no
31                    country of birth father  None            yes
32                    country of birth mother  None            yes
33                      country of birth self  None             no
34                                citizenship  None             no
35              own business or self employed  None             no
36  fill inc questionaire for veteran's admin  None             no
37                          veterans benefits  None             no
38                       weeks worked in year  None             no
39                        below or above $50k  None             no
40                              wage per hour  None             no
41                                   94 or 95  None             no

In [17]:
X

,AAGE,ACLSWKR,ADTINK,ADTOCC,AHGA,AHSCOL,AMARITL,AMJIND,AMJOCC,ARACE,...,PEFNTVTY,PEMNTVTY,PENATVTY,PRCITSHP,SEOTR,VETQVA,VETYN,WKSWORK,AHRSPAY,year
0,73,Not in universe,0,0,High school graduate,Not in universe,Widowed,Not in universe or children,Not in universe,White,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,0,95
1,58,Self-employed-not incorporated,4,34,Some college but no degree,Not in universe,Divorced,Construction,Precision production craft & repair,White,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,0,94
2,18,Not in universe,0,0,10th grade,High school,Never married,Not in universe or children,Not in universe,Asian or Pacific Islander,...,Vietnam,Vietnam,Vietnam,Foreign born- Not a citizen of U S,0,Not in universe,2,0,0,95
3,9,Not in universe,0,0,Children,Not in universe,Never married,Not in universe or children,Not in universe,White,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,0,94
4,10,Not in universe,0,0,Children,Not in universe,Never married,Not in universe or children,Not in universe,White,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,0,94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199518,87,Not in universe,0,0,7th and 8th grade,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,White,...,Canada,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,0,95
199519,65,Self-employed-incorporated,37,2,11th grade,Not in universe,Married-civilian spouse present,Business and repair services,Executive admin and managerial,White,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,0,94
199520,47,Not in universe,0,0,Some college but no degree,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,White,...,Poland,Poland,Germany,Foreign born- U S citizen by naturalization,0,Not in universe,2,52,0,95
199521,16,Not in universe,0,0,10th grade,High school,Never married,Not in universe or children,Not in universe,White,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,0,95
199522,32,Private,42,30,High school graduate,Not in universe,Never married,Medical except hospital,Other service,Black,...,NaN,NaN,NaN,Foreign born- Not a citizen of U S,0,Not in universe,2,52,0,94

In [18]:
# reading from zip file is the same as uciml api
# df_trash = pd.read_csv("D:\SummerResearch\data\census2\census-income.data")
# df_trash

In [19]:
X.isnull().sum()

AAGE             0
ACLSWKR          0
ADTINK           0
ADTOCC           0
AHGA             0
AHSCOL           0
AMARITL          0
AMJIND           0
AMJOCC           0
ARACE            0
AREORGN          0
ASEX             0
AUNMEM           0
AUNTYPE          0
AWKSTAT          0
CAPGAIN          0
GAPLOSS          0
DIVVAL           0
FILESTAT         0
GRINREG          0
GRINST         708
HHDFMX           0
HHDREL           0
MARSUPWRT        0
MIGMTR1      99696
MIGMTR3      99696
MIGMTR4      99696
MIGSAME          0
MIGSUN       99696
NOEMP            0
PARENT           0
PEFNTVTY      6713
PEMNTVTY      6119
PENATVTY      3393
PRCITSHP         0
SEOTR            0
VETQVA           0
VETYN            0
WKSWORK          0
AHRSPAY          0
year             0
dtype: int64

In [20]:
X.drop(columns=['MIGMTR1', 'MIGMTR3', 'MIGMTR4', 'MIGSUN'], inplace=True)
X.dropna(inplace=True)
X

C:\Users\admin\AppData\Local\Temp\ipykernel_18204\2184146956.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.drop(columns=['MIGMTR1', 'MIGMTR3', 'MIGMTR4', 'MIGSUN'], inplace=True)
C:\Users\admin\AppData\Local\Temp\ipykernel_18204\2184146956.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.dropna(inplace=True)

,AAGE,ACLSWKR,ADTINK,ADTOCC,AHGA,AHSCOL,AMARITL,AMJIND,AMJOCC,ARACE,...,PEFNTVTY,PEMNTVTY,PENATVTY,PRCITSHP,SEOTR,VETQVA,VETYN,WKSWORK,AHRSPAY,year
0,73,Not in universe,0,0,High school graduate,Not in universe,Widowed,Not in universe or children,Not in universe,White,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,0,95
1,58,Self-employed-not incorporated,4,34,Some college but no degree,Not in universe,Divorced,Construction,Precision production craft & repair,White,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,0,94
2,18,Not in universe,0,0,10th grade,High school,Never married,Not in universe or children,Not in universe,Asian or Pacific Islander,...,Vietnam,Vietnam,Vietnam,Foreign born- Not a citizen of U S,0,Not in universe,2,0,0,95
3,9,Not in universe,0,0,Children,Not in universe,Never married,Not in universe or children,Not in universe,White,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,0,94
4,10,Not in universe,0,0,Children,Not in universe,Never married,Not in universe or children,Not in universe,White,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,0,94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199517,39,Private,43,26,Bachelors degree(BA AB BS),Not in universe,Never married,Education,Adm support including clerical,Other,...,Mexico,Mexico,Mexico,Foreign born- Not a citizen of U S,2,Not in universe,2,52,0,95
199518,87,Not in universe,0,0,7th and 8th grade,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,White,...,Canada,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,0,95
199519,65,Self-employed-incorporated,37,2,11th grade,Not in universe,Married-civilian spouse present,Business and repair services,Executive admin and managerial,White,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,0,94
199520,47,Not in universe,0,0,Some college but no degree,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,White,...,Poland,Poland,Germany,Foreign born- U S citizen by naturalization,0,Not in universe,2,52,0,95
199521,16,Not in universe,0,0,10th grade,High school,Never married,Not in universe or children,Not in universe,White,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,0,95